Fix Uncaught TypeError: s.split is not a function
This is conflict with Gutenberg due to it sometimes sendind FormData
objects instead of JSON.
Fix #262